build:
  maxIssues: 0

complexity:
  LongMethod:
    threshold: 60
  LongParameterList:
    functionThreshold: 6
    constructorThreshold: 8
  TooManyFunctions:
    thresholdInFiles: 15
    thresholdInClasses: 15

naming:
  FunctionNaming:
    functionPattern: '[a-zA-Z][a-zA-Z0-9]*'
  TopLevelPropertyNaming:
    constantPattern: '[A-Z][A-Za-z0-9]*'

style:
  MagicNumber:
    active: false
  WildcardImport:
    active: false
  MaxLineLength:
    maxLineLength: 120
  ReturnCount:
    max: 3
